# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e918870978790d020a77ac45298772003dc78f38cad0abb311fe9c5f1ea4baa4e1288bacef7fa10b3bff1d751d56e3136459dbb6e1ffd8cf265e0b94ead753d3

test:
  secret_key_base: 9e4a10fd77c931e7be68b643186575505f0e2c418a7d22a721ceb4f9391107dde24962ea21c68cec8c5db99752613a7e7078720bcf21b0b9fcdbe4ec1dc26ed4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
